# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180505_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityareamapping',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day']},
        ),
    ]
